export const VALIDATE_MESSAGES = {
  REQUIRED: 'required',
  INVALID_NUMBER: 'invalid-number',
  LESS_OR_EQUAL: 'less-or-equal',
  LARGER_OR_EQUAL: 'larger-or-equal',
  TRIM: 'trim',
  ONE_DECIMAL: 'one-decimal',
  DATE_FORMAT: 'date-format',
  SPECIAL_CHARACTERS: 'special-characters',
  NUMBER: 'number',
  MAX_LENGTH: 'max-length',
  SPECIAL_CHARACTERS_PARTER_NAME: 'special-characters-parter-name',
  SPECIAL_CHARACTERS_SUPPLIER_NAME: 'special-characters-supplier-name',
  INVALID_PASSWORD_SPECIAL_CHAR: 'invalid-password-special',
  NO_NUMBER: 'no-number',
  INVALID_EMAIL: 'invalid-email',
  PHONE_NUMBER: 'invalid-phone-number',
  INTERGER: 'number-integer',
  MAX_PHONE_NUMBER: 'phone-number-max',
  FORMAT_PHONE_NUMBER: 'phone-number-format',
  INVALID_PASSWORD_MIN: 'invalid-password-min',
  INVALID_PASSWORD_MAX: 'invalid-password-max',
};
